# Generated by Django 2.1.4 on 2019-01-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='order_date')),
                ('currency', models.CharField(max_length=3, verbose_name='order_currency')),
                ('total_cost', models.PositiveIntegerField(verbose_name='order_total_cost')),
                ('delivery_country', models.CharField(max_length=3, verbose_name='order_delivery')),
                ('is_paid', models.BooleanField(verbose_name='order_paid')),
                ('is_delivered', models.BooleanField(verbose_name='order_delivered')),
                ('is_fake', models.BooleanField(verbose_name='order_is_fake')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemPCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='item_type')),
                ('quantity', models.SmallIntegerField(verbose_name='item_quantity')),
                ('size', models.CharField(max_length=10, verbose_name='pcb_item_size')),
                ('material', models.CharField(max_length=100, verbose_name='pcb_item_material')),
                ('thickness', models.FloatField(verbose_name='pcb_item_thickness')),
                ('color', models.CharField(max_length=15, verbose_name='pcb_item_color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_app.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
