# Generated by Django 2.1.5 on 2019-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='order_delivered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_fake',
            field=models.BooleanField(default=False, verbose_name='order_is_fake'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='order_paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='order_total_cost'),
        ),
        migrations.AlterField(
            model_name='orderitempcb',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='item_quantity'),
        ),
    ]
