# Generated by Django 2.1.5 on 2019-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_app', '0002_auto_20190114_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitempcb',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='pcb_item_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0, verbose_name='order_total_cost'),
        ),
    ]
