# Generated by Django 2.1.5 on 2019-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_app', '0003_auto_20190115_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivered',
            field=models.CharField(max_length=30, verbose_name='order_delivered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_fake',
            field=models.CharField(max_length=30, verbose_name='order_is_fake'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(max_length=30, verbose_name='order_paid'),
        ),
    ]
