# Generated by Django 2.1.5 on 2019-01-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_app', '0004_auto_20190115_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='price_list_creation_date')),
                ('sku_id', models.CharField(max_length=100, verbose_name='price_list_item_sku_id')),
                ('price', models.PositiveIntegerField(verbose_name='price_list_item_price')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='vendor_name')),
                ('country', models.CharField(max_length=100, verbose_name='vendor_country')),
                ('currency', models.CharField(max_length=100, verbose_name='vendor_currency')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_app.Vendor'),
        ),
    ]
