# Generated by Django 2.1.5 on 2019-01-17 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_app', '0005_auto_20190117_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, verbose_name='sku_id')),
                ('section_name', models.CharField(max_length=50, verbose_name='sku_section_name')),
                ('type_name', models.CharField(max_length=10, verbose_name='sku_type_name')),
                ('value', models.CharField(max_length=10, verbose_name='sku_value')),
                ('description', models.CharField(max_length=100, verbose_name='sku_friendly_description')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='inventory_sku_price')),
                ('reserve', models.SmallIntegerField(default=0, verbose_name='inventory_sku_reserve')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='inventory_sku_last_update_time')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_app.Sku')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_app.Vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='vendor',
        ),
        migrations.AddField(
            model_name='orderitempcb',
            name='sku_id',
            field=models.CharField(default=datetime.datetime(2019, 1, 17, 11, 1, 29, 729293, tzinfo=utc), max_length=100, verbose_name='item_sku'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
